#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-oauthlib
Version  : 3.2.0
Release  : 70
URL      : https://files.pythonhosted.org/packages/6e/7e/a43cec8b2df28b6494a865324f0ac4be213cb2edcf1e2a717547a93279b0/oauthlib-3.2.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/6e/7e/a43cec8b2df28b6494a865324f0ac4be213cb2edcf1e2a717547a93279b0/oauthlib-3.2.0.tar.gz
Summary  : A generic, spec-compliant, thorough implementation of the OAuth request-signing logic
Group    : Development/Tools
License  : BSD-3-Clause
Requires: pypi-oauthlib-license = %{version}-%{release}
Requires: pypi-oauthlib-python = %{version}-%{release}
Requires: pypi-oauthlib-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
OAuthLib - Python Framework for OAuth1 & OAuth2
===============================================

%package license
Summary: license components for the pypi-oauthlib package.
Group: Default

%description license
license components for the pypi-oauthlib package.


%package python
Summary: python components for the pypi-oauthlib package.
Group: Default
Requires: pypi-oauthlib-python3 = %{version}-%{release}

%description python
python components for the pypi-oauthlib package.


%package python3
Summary: python3 components for the pypi-oauthlib package.
Group: Default
Requires: python3-core
Provides: pypi(oauthlib)

%description python3
python3 components for the pypi-oauthlib package.


%prep
%setup -q -n oauthlib-3.2.0
cd %{_builddir}/oauthlib-3.2.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1643583692
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-oauthlib
cp %{_builddir}/oauthlib-3.2.0/LICENSE %{buildroot}/usr/share/package-licenses/pypi-oauthlib/5f350c5a2f0fb712d78b3203f40d1f9d3b399a31
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-oauthlib/5f350c5a2f0fb712d78b3203f40d1f9d3b399a31

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
